packages:
  - apps/web
  - packages/*

allowBuilds:
  better-sqlite3: true

minimumReleaseAgeExclude:
  - '@next/*'
  - next
  - baseline-browser-mapping@2.11.23

overrides:
  baseline-browser-mapping: 2.11.23
  browserslist: 4.28.9
