'use client'

import { useState } from 'react'
import { ArrowUpRight, Bot, Check, ChevronRight, Clock3, Command, FileText, LayoutDashboard, Menu, Plus, Search, Settings2, Sparkles, X } from 'lucide-react'

const projects = [
  { name: 'Q3 Growth Strategy', type: 'Strategy', status: 'Active', updated: '2m ago', color: 'bg-cyan-400' },
  { name: 'Product Launch 2025', type: 'Launch plan', status: 'Draft', updated: '1h ago', color: 'bg-violet-400' },
  { name: 'Brand Voice System', type: 'Brand', status: 'Active', updated: 'Yesterday', color: 'bg-amber-300' },
]

const activity = [
  ['Strategy agent completed a brief', 'Q3 Growth Strategy', '4 min ago'],
  ['You added a new source', 'Product Launch 2025', '1 hour ago'],
  ['Brand agent updated tone guidelines', 'Brand Voice System', 'Yesterday'],
]

function NavItem({ icon: Icon, label, active = false }: { icon: typeof LayoutDashboard; label: string; active?: boolean }) {
  return <button className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm transition-colors ${active ? 'bg-primary text-primary-foreground' : 'text-muted-foreground hover:bg-accent hover:text-foreground'}`}><Icon className="size-4" />{label}</button>
}

export function HarikosShell() {
  const [mobileOpen, setMobileOpen] = useState(false)
  const [query, setQuery] = useState('')
  const [prompt, setPrompt] = useState('')
  const [sent, setSent] = useState(false)
  const filtered = projects.filter((p) => p.name.toLowerCase().includes(query.toLowerCase()))

  return <div className="min-h-screen bg-background text-foreground">
    <aside className={`fixed inset-y-0 left-0 z-20 flex w-64 flex-col border-r border-border bg-card px-4 py-5 transition-transform md:translate-x-0 ${mobileOpen ? 'translate-x-0' : '-translate-x-full'}`}>
      <div className="mb-10 flex items-center justify-between px-2"><div className="flex items-center gap-2.5"><div className="grid size-8 place-items-center rounded-lg bg-primary text-primary-foreground"><Sparkles className="size-4" /></div><span className="font-semibold tracking-tight">harikos<span className="text-primary">.</span>ai</span></div><button className="md:hidden" onClick={() => setMobileOpen(false)} aria-label="Close navigation"><X className="size-5" /></button></div>
      <div className="flex flex-col gap-1"><NavItem icon={LayoutDashboard} label="Overview" active /><NavItem icon={FileText} label="Projects" /><NavItem icon={Bot} label="Agents" /><NavItem icon={Clock3} label="Activity" /></div>
      <div className="mt-auto flex flex-col gap-1"><NavItem icon={Settings2} label="Settings" /><div className="mt-5 flex items-center gap-3 border-t border-border px-2 pt-5"><div className="grid size-8 place-items-center rounded-full bg-secondary text-xs font-semibold">AY</div><div className="min-w-0"><p className="truncate text-sm font-medium">Ash Yeager</p><p className="truncate text-xs text-muted-foreground">Personal workspace</p></div></div></div>
    </aside>
    {mobileOpen && <button className="fixed inset-0 z-10 bg-foreground/20 md:hidden" onClick={() => setMobileOpen(false)} aria-label="Close navigation overlay" />}
    <main className="md:pl-64"><header className="flex h-16 items-center justify-between border-b border-border px-5 md:px-10"><div className="flex items-center gap-3"><button className="md:hidden" onClick={() => setMobileOpen(true)} aria-label="Open navigation"><Menu className="size-5" /></button><p className="text-sm text-muted-foreground">Wednesday, August 27, 2026</p></div><div className="flex items-center gap-3"><button className="hidden items-center gap-2 rounded-lg border border-border px-3 py-1.5 text-xs text-muted-foreground md:flex"><Command className="size-3" />K</button><button className="grid size-8 place-items-center rounded-full bg-secondary text-xs font-semibold">AY</button></div></header>
      <div className="mx-auto max-w-7xl px-5 py-8 md:px-10 md:py-12"><div className="mb-10 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="mb-3 text-sm font-medium text-primary">Your workspace</p><h1 className="text-balance text-3xl font-semibold tracking-tight md:text-4xl">Good morning, Ash.</h1><p className="mt-2 text-muted-foreground">Make space for the work that matters.</p></div><button className="flex items-center justify-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-sm font-medium text-primary-foreground transition-transform hover:-translate-y-0.5"><Plus className="size-4" /> New project</button></div>
        <section className="mb-10 grid gap-4 lg:grid-cols-[1.5fr_1fr]"><div className="relative overflow-hidden rounded-2xl bg-primary p-6 text-primary-foreground md:p-8"><div className="relative z-[1] max-w-lg"><div className="mb-5 flex size-10 items-center justify-center rounded-xl bg-primary-foreground/15"><Sparkles className="size-5" /></div><h2 className="text-2xl font-semibold tracking-tight md:text-3xl">What are you working on?</h2><p className="mt-2 max-w-sm text-sm leading-relaxed text-primary-foreground/70">Start a project, explore an idea, or let an agent help you move faster.</p><div className="mt-7 flex items-center gap-2 rounded-xl bg-primary-foreground/10 p-2 ring-1 ring-primary-foreground/15"><input value={prompt} onChange={(e) => { setPrompt(e.target.value); setSent(false) }} onKeyDown={(e) => { if (e.key === 'Enter' && !e.nativeEvent.isComposing && e.keyCode !== 229) setSent(true) }} placeholder="Describe what you want to make..." className="min-w-0 flex-1 bg-transparent px-2 text-sm outline-none placeholder:text-primary-foreground/45" /><button onClick={() => setSent(true)} className="grid size-9 shrink-0 place-items-center rounded-lg bg-primary-foreground text-primary"><ArrowUpRight className="size-4" /></button></div>{sent && <p className="mt-3 flex items-center gap-2 text-xs text-primary-foreground/80"><Check className="size-3" />Got it — your idea is ready to become a project.</p>}</div><div className="pointer-events-none absolute -right-10 -top-20 size-64 rounded-full border border-primary-foreground/10" /></div><div className="rounded-2xl border border-border bg-card p-6 md:p-8"><div className="mb-6 flex items-center justify-between"><div><p className="text-sm font-medium">Workspace pulse</p><p className="mt-1 text-xs text-muted-foreground">Your momentum this week</p></div><span className="rounded-full bg-secondary px-2.5 py-1 text-xs font-medium text-muted-foreground">This week</span></div><div className="flex items-end gap-2" aria-label="Activity chart"><div className="h-12 flex-1 rounded-t-md bg-secondary" /><div className="h-20 flex-1 rounded-t-md bg-secondary" /><div className="h-16 flex-1 rounded-t-md bg-secondary" /><div className="h-28 flex-1 rounded-t-md bg-primary" /><div className="h-24 flex-1 rounded-t-md bg-primary/70" /><div className="h-36 flex-1 rounded-t-md bg-primary" /><div className="h-32 flex-1 rounded-t-md bg-primary/70" /></div><div className="mt-3 flex justify-between text-[11px] text-muted-foreground"><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span><span>Sun</span></div></div></section>
        <section><div className="mb-4 flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h2 className="text-lg font-semibold">Recent projects</h2><p className="text-sm text-muted-foreground">Pick up where you left off.</p></div><div className="flex items-center gap-2 rounded-lg border border-border px-3 py-2"><Search className="size-4 text-muted-foreground" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search projects" className="w-full bg-transparent text-sm outline-none placeholder:text-muted-foreground sm:w-40" /></div></div><div className="grid gap-4 lg:grid-cols-3">{filtered.map((project) => <button key={project.name} className="group rounded-2xl border border-border bg-card p-5 text-left transition-all hover:-translate-y-0.5 hover:border-primary/50 hover:shadow-sm"><div className={`mb-8 size-3 rounded-full ${project.color}`} /><div className="flex items-start justify-between gap-3"><div><h3 className="font-medium">{project.name}</h3><p className="mt-1 text-sm text-muted-foreground">{project.type}</p></div><ChevronRight className="size-4 text-muted-foreground transition-transform group-hover:translate-x-1" /></div><div className="mt-5 flex items-center justify-between text-xs text-muted-foreground"><span className="rounded-full bg-secondary px-2.5 py-1">{project.status}</span><span>{project.updated}</span></div></button>)}</div></section>
        <section className="mt-10 border-t border-border pt-8"><h2 className="mb-4 text-lg font-semibold">Recent activity</h2><div className="flex flex-col gap-4">{activity.map(([title, project, time]) => <div key={title} className="flex items-center gap-3"><div className="grid size-8 shrink-0 place-items-center rounded-full bg-secondary"><Check className="size-4 text-primary" /></div><div className="min-w-0 flex-1"><p className="truncate text-sm">{title}</p><p className="truncate text-xs text-muted-foreground">{project}</p></div><time className="text-xs text-muted-foreground">{time}</time></div>)}</div></section>
      </div></main>
  </div>
}

export default HarikosShell
